version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: child_exchange
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://user:password@postgres:5432/child_exchange
      - JWT_SECRET=R329!gklsM3@lkf2k3T8%lS0w1T7gD6p4R5b
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads  # Монтируем папку uploads
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: